# fly.toml app configuration file generated for anniexboda-ifog6q on 2026-05-16T17:03:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anniexboda-ifog6q"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"
  TMPDIR = "/dev/shm"
  IP_VERSION = "4"
  OMP_NUM_THREADS = "10"
  MKL_NUM_THREADS = "10"
  NUMEXPR_NUM_THREADS = "10"

[sysctl]
  "net.core.default_qdisc" = "fq"
  "net.ipv4.tcp_congestion_control" = "bbr"
  "net.core.rmem_max" = "16777216"
  "net.core.wmem_max" = "16777216"
  "net.ipv4.tcp_rmem" = "4096 87380 16777216"
  "net.ipv4.tcp_wmem" = "4096 65536 16777216"
  "net.ipv4.tcp_window_scaling" = "1"
  "net.ipv4.tcp_slow_start_after_idle" = "0"

[[vm]]
  cpu_kind = 'performance'
  cpus = 10
  memory_mb = 66560
