# fly.toml app configuration file generated for anniexboda-ifog6q on 2026-04-23T17:12:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anniexboda-ifog6q'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  IP_VERSION = '4'
  MKL_NUM_THREADS = '10'
  NUMEXPR_NUM_THREADS = '10'
  OMP_NUM_THREADS = '10'
  PYTHONDONTWRITEBYTECODE = '1'
  PYTHONUNBUFFERED = '1'
  TMPDIR = '/dev/shm'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'performance'
  cpus = 10
  memory_mb = 66560
